// Subconjunto representativo del catálogo CIE-10 (~80 códigos frecuentes en atención
// primaria y salud mental). El seed hace upsert por código: para cargar el catálogo
// completo basta ampliar esta lista o importar y reutilizar la misma rutina.
const CIE10 = [
  // Salud mental
  { codigo: 'F32.0', descripcion: 'Episodio depresivo leve' },
  { codigo: 'F32.1', descripcion: 'Episodio depresivo moderado' },
  { codigo: 'F32.9', descripcion: 'Episodio depresivo, no especificado' },
  { codigo: 'F33.1', descripcion: 'Trastorno depresivo recurrente, episodio moderado presente' },
  { codigo: 'F41.0', descripcion: 'Trastorno de pánico (ansiedad paroxística episódica)' },
  { codigo: 'F41.1', descripcion: 'Trastorno de ansiedad generalizada' },
  { codigo: 'F41.2', descripcion: 'Trastorno mixto de ansiedad y depresión' },
  { codigo: 'F43.0', descripcion: 'Reacción al estrés agudo' },
  { codigo: 'F43.1', descripcion: 'Trastorno de estrés postraumático' },
  { codigo: 'F43.2', descripcion: 'Trastornos de adaptación' },
  { codigo: 'F51.0', descripcion: 'Insomnio no orgánico' },
  { codigo: 'F60.3', descripcion: 'Trastorno de la personalidad emocionalmente inestable' },
  { codigo: 'F84.0', descripcion: 'Autismo en la niñez' },
  { codigo: 'F90.0', descripcion: 'Perturbación de la actividad y de la atención' },
  { codigo: 'F95.1', descripcion: 'Trastorno de tics motores o vocales crónicos' },
  // Circulatorio / metabólico
  { codigo: 'I10X', descripcion: 'Hipertensión esencial (primaria)' },
  { codigo: 'I25.1', descripcion: 'Enfermedad aterosclerótica del corazón' },
  { codigo: 'I48.9', descripcion: 'Fibrilación y aleteo auricular, no especificado' },
  { codigo: 'I50.9', descripcion: 'Insuficiencia cardíaca, no especificada' },
  { codigo: 'E03.9', descripcion: 'Hipotiroidismo, no especificado' },
  { codigo: 'E05.9', descripcion: 'Tirotoxicosis, no especificada' },
  { codigo: 'E11.9', descripcion: 'Diabetes mellitus tipo 2 sin complicaciones' },
  { codigo: 'E11.2', descripcion: 'Diabetes mellitus tipo 2 con complicaciones renales' },
  { codigo: 'E66.9', descripcion: 'Obesidad, no especificada' },
  { codigo: 'E78.0', descripcion: 'Hipercolesterolemia pura' },
  { codigo: 'E78.5', descripcion: 'Hiperlipidemia no especificada' },
  { codigo: 'E86', descripcion: 'Depleción del volumen (deshidratación)' },
  // Respiratorio
  { codigo: 'J00X', descripcion: 'Rinofaringitis aguda (resfriado común)' },
  { codigo: 'J02.9', descripcion: 'Faringitis aguda, no especificada' },
  { codigo: 'J03.9', descripcion: 'Amigdalitis aguda, no especificada' },
  { codigo: 'J06.9', descripcion: 'Infección aguda de las vías respiratorias superiores, no especificada' },
  { codigo: 'J18.9', descripcion: 'Neumonía, no especificada' },
  { codigo: 'J20.9', descripcion: 'Bronquitis aguda, no especificada' },
  { codigo: 'J30.4', descripcion: 'Rinitis alérgica, no especificada' },
  { codigo: 'J45.0', descripcion: 'Asma predominantemente alérgica' },
  { codigo: 'J45.9', descripcion: 'Asma, no especificada' },
  { codigo: 'J44.9', descripcion: 'Enfermedad pulmonar obstructiva crónica, no especificada' },
  // Digestivo
  { codigo: 'K02.9', descripcion: 'Caries dental, no especificada' },
  { codigo: 'K04.7', descripcion: 'Absceso periapical sin fístula' },
  { codigo: 'K05.1', descripcion: 'Gingivitis crónica' },
  { codigo: 'K21.0', descripcion: 'Enfermedad del reflujo gastroesofágico con esofagitis' },
  { codigo: 'K29.7', descripcion: 'Gastritis, no especificada' },
  { codigo: 'K30X', descripcion: 'Dispepsia funcional' },
  { codigo: 'K59.0', descripcion: 'Constipación' },
  { codigo: 'A09X', descripcion: 'Diarrea y gastroenteritis de presunto origen infeccioso' },
  // Genitourinario / gineco
  { codigo: 'N39.0', descripcion: 'Infección de vías urinarias, sitio no especificado' },
  { codigo: 'N76.0', descripcion: 'Vaginitis aguda' },
  { codigo: 'N94.6', descripcion: 'Dismenorrea, no especificada' },
  { codigo: 'Z34.9', descripcion: 'Supervisión de embarazo normal, no especificado' },
  { codigo: 'O26.9', descripcion: 'Complicación relacionada con el embarazo, no especificada' },
  // Osteomuscular
  { codigo: 'M25.5', descripcion: 'Dolor en articulación' },
  { codigo: 'M54.4', descripcion: 'Lumbago con ciática' },
  { codigo: 'M54.5', descripcion: 'Lumbago no especificado' },
  { codigo: 'M62.6', descripcion: 'Contractura muscular' },
  { codigo: 'M79.1', descripcion: 'Mialgia' },
  { codigo: 'M17.9', descripcion: 'Gonartrosis, no especificada' },
  // Neuro / general
  { codigo: 'G43.9', descripcion: 'Migraña, no especificada' },
  { codigo: 'G44.2', descripcion: 'Cefalea tensional' },
  { codigo: 'G47.0', descripcion: 'Trastornos del inicio y del mantenimiento del sueño' },
  { codigo: 'R05X', descripcion: 'Tos' },
  { codigo: 'R10.4', descripcion: 'Otros dolores abdominales y los no especificados' },
  { codigo: 'R50.9', descripcion: 'Fiebre, no especificada' },
  { codigo: 'R51X', descripcion: 'Cefalea' },
  { codigo: 'R53X', descripcion: 'Malestar y fatiga' },
  { codigo: 'R42X', descripcion: 'Mareo y desvanecimiento' },
  // Piel / infecciosas
  { codigo: 'L20.9', descripcion: 'Dermatitis atópica, no especificada' },
  { codigo: 'L23.9', descripcion: 'Dermatitis alérgica de contacto, de causa no especificada' },
  { codigo: 'L70.0', descripcion: 'Acné vulgar' },
  { codigo: 'B01.9', descripcion: 'Varicela sin complicaciones' },
  { codigo: 'B34.9', descripcion: 'Infección viral, no especificada' },
  // Nutrición
  { codigo: 'E44.1', descripcion: 'Desnutrición proteicocalórica leve' },
  { codigo: 'E63.9', descripcion: 'Deficiencia nutricional, no especificada' },
  { codigo: 'R63.4', descripcion: 'Pérdida anormal de peso' },
  { codigo: 'R63.5', descripcion: 'Aumento anormal de peso' },
  // Códigos Z (factores que influyen en el estado de salud)
  { codigo: 'Z00.0', descripcion: 'Examen médico general' },
  { codigo: 'Z01.2', descripcion: 'Examen odontológico' },
  { codigo: 'Z13.3', descripcion: 'Examen de pesquisa especial para trastornos mentales y del comportamiento' },
  { codigo: 'Z63.0', descripcion: 'Problemas en la relación con el cónyuge o la pareja' },
  { codigo: 'Z71.1', descripcion: 'Persona que teme estar enferma, a quien no se hace diagnóstico' },
  { codigo: 'Z76.0', descripcion: 'Consulta para repetición de receta' },
];

module.exports = { CIE10 };
