// Subconjunto representativo del catálogo CUPS (~80 códigos frecuentes en laboratorio
// clínico e imagenología). El seed hace upsert por código: para cargar el catálogo
// completo basta ampliar esta lista o importar y reutilizar la misma rutina.
const CUPS = [
  // Hematología
  { codigo: '902210', nombre: 'Hemograma completo' },
  { codigo: '902207', nombre: 'Hemoglobina y hematocrito' },
  { codigo: '902229', nombre: 'Velocidad de sedimentación globular (VSG)' },
  { codigo: '902303', nombre: 'Tiempo de protrombina (PT)' },
  { codigo: '902304', nombre: 'Tiempo parcial de tromboplastina (PTT)' },
  { codigo: '902221', nombre: 'Recuento de plaquetas' },
  { codigo: '902401', nombre: 'Grupo sanguíneo y factor Rh' },
  // Química sanguínea
  { codigo: '903841', nombre: 'Glicemia basal' },
  { codigo: '903842', nombre: 'Glicemia post-carga (2 horas)' },
  { codigo: '903849', nombre: 'Hemoglobina glicosilada (HbA1c)' },
  { codigo: '903872', nombre: 'Perfil lipídico (colesterol total, HDL, LDL, triglicéridos)' },
  { codigo: '903880', nombre: 'Creatinina sérica' },
  { codigo: '903895', nombre: 'Nitrógeno ureico (BUN)' },
  { codigo: '903900', nombre: 'Ácido úrico' },
  { codigo: '903890', nombre: 'Transaminasa glutámico pirúvica (ALT/TGP)' },
  { codigo: '903891', nombre: 'Transaminasa glutámico oxalacética (AST/TGO)' },
  { codigo: '903905', nombre: 'Bilirrubinas totales y directas' },
  { codigo: '903910', nombre: 'Fosfatasa alcalina' },
  { codigo: '903915', nombre: 'Proteínas totales y albúmina' },
  { codigo: '903920', nombre: 'Electrolitos (sodio, potasio, cloro)' },
  { codigo: '903925', nombre: 'Calcio sérico' },
  { codigo: '903930', nombre: 'Fósforo sérico' },
  { codigo: '903935', nombre: 'Magnesio sérico' },
  // Endocrinología
  { codigo: '903833', nombre: 'Hormona estimulante de tiroides (TSH)' },
  { codigo: '903834', nombre: 'T4 libre' },
  { codigo: '903835', nombre: 'T3 total' },
  { codigo: '903960', nombre: 'Cortisol sérico' },
  { codigo: '903965', nombre: 'Insulina basal' },
  { codigo: '903970', nombre: 'Antígeno prostático específico (PSA)' },
  // Uroanálisis y coprología
  { codigo: '907106', nombre: 'Uroanálisis completo' },
  { codigo: '907110', nombre: 'Urocultivo con antibiograma' },
  { codigo: '907230', nombre: 'Coprológico y coproscópico' },
  { codigo: '907235', nombre: 'Sangre oculta en materia fecal' },
  // Serología e infecciosas
  { codigo: '906227', nombre: 'VIH (prueba de tamizaje)' },
  { codigo: '906230', nombre: 'VDRL (sífilis)' },
  { codigo: '906235', nombre: 'Hepatitis B (antígeno de superficie)' },
  { codigo: '906240', nombre: 'Hepatitis C (anticuerpos)' },
  { codigo: '906250', nombre: 'Prueba de embarazo en sangre (beta-hCG)' },
  { codigo: '906260', nombre: 'Proteína C reactiva (PCR)' },
  { codigo: '906270', nombre: 'Factor reumatoide' },
  { codigo: '906280', nombre: 'Antiestreptolisinas O (ASTO)' },
  // Imagenología - Radiografía
  { codigo: '881234', nombre: 'Radiografía de tórax PA' },
  { codigo: '881235', nombre: 'Radiografía de tórax lateral' },
  { codigo: '881301', nombre: 'Radiografía de columna lumbosacra' },
  { codigo: '881302', nombre: 'Radiografía de columna cervical' },
  { codigo: '881401', nombre: 'Radiografía de rodilla' },
  { codigo: '881402', nombre: 'Radiografía de hombro' },
  { codigo: '881403', nombre: 'Radiografía de mano' },
  { codigo: '881404', nombre: 'Radiografía de pie' },
  { codigo: '881501', nombre: 'Radiografía de abdomen simple' },
  { codigo: '881601', nombre: 'Radiografía de cráneo' },
  // Imagenología - Ecografía
  { codigo: '881801', nombre: 'Ecografía abdominal total' },
  { codigo: '881802', nombre: 'Ecografía pélvica' },
  { codigo: '881803', nombre: 'Ecografía transvaginal' },
  { codigo: '881804', nombre: 'Ecografía renal y vías urinarias' },
  { codigo: '881805', nombre: 'Ecografía de tiroides' },
  { codigo: '881806', nombre: 'Ecografía obstétrica' },
  { codigo: '881807', nombre: 'Ecografía de tejidos blandos' },
  { codigo: '881808', nombre: 'Ecografía Doppler venoso de miembros inferiores' },
  // Imagenología - Tomografía / Resonancia
  { codigo: '881901', nombre: 'Tomografía axial computarizada de cráneo simple' },
  { codigo: '881902', nombre: 'Tomografía axial computarizada de tórax' },
  { codigo: '881903', nombre: 'Tomografía axial computarizada de abdomen' },
  { codigo: '882001', nombre: 'Resonancia magnética de cerebro' },
  { codigo: '882002', nombre: 'Resonancia magnética de columna lumbar' },
  { codigo: '882003', nombre: 'Resonancia magnética de rodilla' },
  // Cardiología
  { codigo: '891201', nombre: 'Electrocardiograma de reposo' },
  { codigo: '891202', nombre: 'Ecocardiograma transtorácico' },
  { codigo: '891203', nombre: 'Prueba de esfuerzo (ergometría)' },
  { codigo: '891204', nombre: 'Monitoreo Holter de 24 horas' },
  { codigo: '891205', nombre: 'Monitoreo ambulatorio de presión arterial (MAPA)' },
  // Procedimientos menores / consulta
  { codigo: '890201', nombre: 'Consulta de primera vez medicina general' },
  { codigo: '890301', nombre: 'Consulta de control medicina general' },
  { codigo: '890202', nombre: 'Consulta de primera vez por especialista' },
  { codigo: '890302', nombre: 'Consulta de control por especialista' },
  { codigo: '890701', nombre: 'Consulta de primera vez psicología' },
  { codigo: '890702', nombre: 'Consulta de control psicología' },
  { codigo: '890703', nombre: 'Consulta de primera vez psiquiatría' },
  { codigo: '890704', nombre: 'Consulta de control psiquiatría' },
  { codigo: '890801', nombre: 'Consulta de primera vez nutrición y dietética' },
  { codigo: '890802', nombre: 'Consulta de control nutrición y dietética' },
  { codigo: '990201', nombre: 'Curación de heridas menor' },
  { codigo: '990202', nombre: 'Retiro de puntos de sutura' },
  { codigo: '990301', nombre: 'Nebulización' },
  { codigo: '990401', nombre: 'Inyección intramuscular' },
  { codigo: '990402', nombre: 'Toma de muestra de laboratorio (venopunción)' },
];

module.exports = { CUPS };
