// Pacientes demo (basados en el mockup "Pacientes - Lista").
// epsNombre se resuelve contra la tabla Eps al sembrar.
const PACIENTES = [
  {
    tipoDocumento: 'CC', numeroDocumento: '1045678912',
    nombres: 'María Alejandra', apellidos: 'Rodríguez Pérez',
    fechaNacimiento: '1992-03-14', sexo: 'femenino', estadoCivil: 'soltero',
    ocupacion: 'Diseñadora Gráfica', grupoSanguineo: 'O', rh: 'positivo',
    telefono: '300 123 4567', correo: 'maria.rodriguez@mail.com',
    direccion: 'Cra 5 # 10-25', municipio: 'Cartagena', zona: 'urbana',
    epsNombre: 'Nueva EPS', regimen: 'contributivo', nroAfiliacion: 'NE-88213456',
    contactos: [
      { nombre: 'Jorge Rodríguez Salcedo', parentesco: 'Padre', telefono: '311 222 3344', direccion: 'Cra 5 # 10-25, Cartagena' },
      { nombre: 'Ana Pérez Villalba', parentesco: 'Madre', telefono: '312 445 6677', direccion: 'Cra 5 # 10-25, Cartagena' },
    ],
  },
  {
    tipoDocumento: 'CC', numeroDocumento: '987654321',
    nombres: 'Carlos Andrés', apellidos: 'Martínez Gómez',
    fechaNacimiento: '1974-01-20', sexo: 'masculino', estadoCivil: 'casado',
    ocupacion: 'Contador', grupoSanguineo: 'A', rh: 'positivo',
    telefono: '311 456 7890', correo: 'carlos.martinez@mail.com',
    direccion: 'Cll 30 # 18-44', municipio: 'Cartagena', zona: 'urbana',
    epsNombre: 'Sura', regimen: 'contributivo', nroAfiliacion: 'SU-4471209',
    contactos: [{ nombre: 'Lucía Gómez Prada', parentesco: 'Esposa', telefono: '310 555 8899', direccion: 'Cll 30 # 18-44, Cartagena' }],
  },
  {
    tipoDocumento: 'CC', numeroDocumento: '1098234567',
    nombres: 'Luisa Fernanda', apellidos: 'Torres Díaz',
    fechaNacimiento: '1999-05-02', sexo: 'femenino', estadoCivil: 'soltero',
    ocupacion: 'Estudiante', grupoSanguineo: 'B', rh: 'negativo',
    telefono: '320 987 6543', correo: 'luisa.torres@mail.com',
    direccion: 'Av. Pedro de Heredia # 45-12', municipio: 'Cartagena', zona: 'urbana',
    epsNombre: 'Sanitas', regimen: 'contributivo', nroAfiliacion: 'SA-2290871',
    contactos: [{ nombre: 'Marta Díaz Ruiz', parentesco: 'Madre', telefono: '315 667 7788', direccion: 'Av. Pedro de Heredia # 45-12' }],
  },
  {
    tipoDocumento: 'CC', numeroDocumento: '77123456',
    nombres: 'Jorge Eliécer', apellidos: 'Ramírez Castro',
    fechaNacimiento: '1965-02-11', sexo: 'masculino', estadoCivil: 'viudo',
    ocupacion: 'Pensionado', grupoSanguineo: 'O', rh: 'negativo',
    telefono: '315 222 3344', correo: null,
    direccion: 'Vereda La Esperanza', municipio: 'Turbaco', zona: 'rural',
    epsNombre: 'Coosalud', regimen: 'subsidiado', nroAfiliacion: 'CO-1104433',
    contactos: [{ nombre: 'Diana Ramírez López', parentesco: 'Hija', telefono: '301 888 9900', direccion: 'Turbaco' }],
  },
  {
    tipoDocumento: 'CC', numeroDocumento: '1010876234',
    nombres: 'Ana Sofía', apellidos: 'Herrera Molina',
    fechaNacimiento: '2007-06-30', sexo: 'femenino', estadoCivil: 'soltero',
    ocupacion: 'Estudiante', grupoSanguineo: 'AB', rh: 'positivo',
    telefono: '350 111 2233', correo: 'ana.herrera@mail.com',
    direccion: 'Cll 70 # 5-90', municipio: 'Cartagena', zona: 'urbana',
    epsNombre: 'Nueva EPS', regimen: 'contributivo', nroAfiliacion: 'NE-99310022',
    activo: false,
    contactos: [{ nombre: 'Rosa Molina Vega', parentesco: 'Madre', telefono: '313 444 5566', direccion: 'Cll 70 # 5-90, Cartagena' }],
  },
  {
    tipoDocumento: 'CC', numeroDocumento: '876543210',
    nombres: 'Pedro Pablo', apellidos: 'Sánchez Ortiz',
    fechaNacimiento: '1981-09-15', sexo: 'masculino', estadoCivil: 'union_libre',
    ocupacion: 'Comerciante', grupoSanguineo: 'A', rh: 'negativo',
    telefono: '301 654 3210', correo: 'pedro.sanchez@mail.com',
    direccion: 'Bocagrande Cra 1 # 8-20', municipio: 'Cartagena', zona: 'urbana',
    epsNombre: 'Sura', regimen: 'contributivo', nroAfiliacion: 'SU-7789021',
    contactos: [{ nombre: 'Carmen Ortiz Julio', parentesco: 'Hermana', telefono: '317 111 0099', direccion: 'Cartagena' }],
  },
  {
    tipoDocumento: 'CC', numeroDocumento: '1088345678',
    nombres: 'Daniela Valentina', apellidos: 'Cruz Rojas',
    fechaNacimiento: '1995-11-08', sexo: 'femenino', estadoCivil: 'casado',
    ocupacion: 'Enfermera', grupoSanguineo: 'O', rh: 'positivo',
    telefono: '312 789 4561', correo: 'daniela.cruz@mail.com',
    direccion: 'Manga Cll 29 # 21-30', municipio: 'Cartagena', zona: 'urbana',
    epsNombre: 'Sanitas', regimen: 'contributivo', nroAfiliacion: 'SA-6612345',
    contactos: [{ nombre: 'Héctor Cruz Meza', parentesco: 'Esposo', telefono: '304 222 7788', direccion: 'Manga Cll 29 # 21-30' }],
  },
  {
    tipoDocumento: 'CC', numeroDocumento: '79456123',
    nombres: 'Ricardo Antonio', apellidos: 'Vargas Luna',
    fechaNacimiento: '1968-04-25', sexo: 'masculino', estadoCivil: 'divorciado',
    ocupacion: 'Taxista', grupoSanguineo: 'B', rh: 'positivo',
    telefono: '317 333 4455', correo: null,
    direccion: 'Barrio Olaya Sector Central', municipio: 'Cartagena', zona: 'urbana',
    epsNombre: 'Coosalud', regimen: 'subsidiado', nroAfiliacion: 'CO-3320981',
    contactos: [{ nombre: 'Marina Luna Pacheco', parentesco: 'Madre', telefono: '318 990 1122', direccion: 'Cartagena' }],
  },
];

module.exports = { PACIENTES };
